services:
    myshop_admin.image_uploader:
        class: MyShop\AdminBundle\ImageUtil\UploadImageService
        arguments:
            - "@myshop_admin.check_img"
            - "@myshop_admin.image_name_generator"
        calls:
            - ["setUploadImageRootDir", ["%image_upload_dir%"]]

    myshop_admin.check_img:
        class: MyShop\AdminBundle\ImageUtil\CheckImg
        arguments:
            - "%upload_image_type_list%"

    myshop_admin.image_name_generator:
        class: MyShop\AdminBundle\ImageUtil\ImageNameGenerator