services:
    myshop_admin.product_subscriber:
        class: MyShop\AdminBundle\Event\ProductSubscriber
        tags:
            - { name: kernel.event_listener, event: product_add_event, method: onProductAddEvent }
            - { name: kernel.event_listener, event: product_edit_event, method: onProductEditEvent }

    myshop_admin.image_uploader:
        class: MyShop\AdminBundle\ImageUtil\UploadImageService
        arguments:
            - "@myshop_admin.check_img"
            - "@myshop_admin.image_name_generator"
        calls:
            - ["setUploadImageRootDir", ["%image_upload_dir%"]]

    myshop_admin.base_check:
        class: MyShop\AdminBundle\ImageUtil\BaseCheck
        abstract: true
        arguments:
            - "%upload_image_type_list%"

    myshop_admin.check_img:
        class: MyShop\AdminBundle\ImageUtil\CheckImg
        parent: "myshop_admin.base_check"

    myshop_admin.image_name_generator:
        class: MyShop\AdminBundle\ImageUtil\ImageNameGenerator

    myshop_admin.cat_tree_twig_extension:
        class: MyShop\AdminBundle\Twig\MyCustomExtension
        public: false
        tags:
            - { name: twig.extension }

    myshop_admin.product_import_export:
        class: MyShop\AdminBundle\Utils\ProductImportExport
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
