services:
    myshop_admin.my_doctrine_subscriber:
        class: MyShop\AdminBundle\Event\MyDoctrineSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    myshop_admin.product_storage:
        class: MyShop\AdminBundle\Storage\ProductStorage
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@knp_paginator"

    myshop_admin.request_listener:
        class: MyShop\AdminBundle\Event\MyRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    myshop_admin.response_listener:
        class: MyShop\AdminBundle\Event\MyResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    myshop_admin.my_exception_listener:
        class: MyShop\AdminBundle\Event\MyExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    myshop_admin.product_subscriber:
        class: MyShop\AdminBundle\Event\ProductSubscriber
        tags:
            - { name: kernel.event_listener, event: product_add_event, method: onProductAddEvent }
            - { name: kernel.event_listener, event: product_edit_event, method: onProductEditEvent }

    myshop_admin.image_uploader:
        class: MyShop\AdminBundle\ImageUtil\UploadImageService
        arguments:
            - "@myshop_admin.check_img"
            - "@myshop_admin.image_name_generator"
        calls:
            - ["setUploadImageRootDir", ["%image_upload_dir%"]]

    myshop_admin.base_check:
        class: MyShop\AdminBundle\ImageUtil\BaseCheck
        abstract: true
        arguments:
            - "%upload_image_type_list%"

    myshop_admin.check_img:
        class: MyShop\AdminBundle\ImageUtil\CheckImg
        parent: "myshop_admin.base_check"

    myshop_admin.image_name_generator:
        class: MyShop\AdminBundle\ImageUtil\ImageNameGenerator

    myshop_admin.cat_tree_twig_extension:
        class: MyShop\AdminBundle\Twig\MyCustomExtension
        public: false
        tags:
            - { name: twig.extension }

    myshop_admin.product_import_export:
        class: MyShop\AdminBundle\Utils\ProductImportExport
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"