services:
    myshop_admin.check_img:
        class: MyShop\AdminBundle\ImageUtil\CheckImg
        arguments:
            - "%upload_image_type_list%"

    myshop_admin.image_name_generator:
        class: MyShop\AdminBundle\ImageUtil\ImageNameGenerator