services:
    myshop_admin.image_uploader:
        class: MyShop\AdminBundle\ImageUtil\UploadImageService
        arguments:
            - "@myshop_admin.check_img"
            - "@myshop_admin.image_name_generator"
        calls:
            - ["setUploadImageRootDir", ["%image_upload_dir%"]]

    myshop_admin.check_img:
        class: MyShop\AdminBundle\ImageUtil\CheckImg
        arguments:
            - "%my_test_param%"

    myshop_admin.image_name_generator:
        class: MyShop\AdminBundle\ImageUtil\ImageNameGenerator

    myshop_admin.cat_tree_twig_extension:
        class: MyShop\AdminBundle\Twig\MyCustomExtension
        public: false
        tags:
            - { name: twig.extension }