myshop.main_page:
    path:     /
    defaults: { _controller: MyShopDefaultBundle:Default:index }

myshop.product_info:
    path: /product/{id}
    defaults: { _controller: MyShopDefaultBundle:Default:showProduct }
    methods: [GET]
    requirements:
        id: \d+

myshop.product_list:
    path: /product/list
    defaults: { _controller: MyShopDefaultBundle:Default:showProductList }

myshop.product_create:
    path: /product/create
    defaults: { _controller: MyShopDefaultBundle:Default:createSomeProduct }


myshop.api.product_details:
    path:   /api/rest/product/{id}.json
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:details }

myshop.api.product_details_xml:
    path:   /api/rest/product/{id}.xml
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:detailsXml }

myshop.api.xml.product_details:
    path:   /api/product/{id}.xml
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:detailsXml }
    requirements:
        id: \d+

myshop.api.json.product_details:
    path:   /api/product/{id}.json
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:detailsJson }
    requirements:
        id: \d+

myshop.api.json_rpc:
    path:   /api/jsonrpc
    defaults: { _controller: MyShopDefaultBundle:API/JsonRPC/JsonRpc:index }

login_customer:
    path: /customer/login
    defaults: { _controller: MyShopDefaultBundle:Customer:login }

customer_logout:
    path: /customer/logout

new_customer:
    path: /customer/registration
    defaults: { _controller: MyShopDefaultBundle:Customer:new }

myshop.basket:
    path: /basket
    defaults: { _controller: MyShopDefaultBundle:Basket:index }

myshop.basket_history:
    path: /basket/history
    defaults: { _controller: MyShopDefaultBundle:Basket:history }

myshop.basket_release:
    path: /basket/confirm
    defaults: { _controller: MyShopDefaultBundle:Basket:releaseOrder }

myshop.basket_reject:
    path: /basket/reject
    defaults: { _controller: MyShopDefaultBundle:Basket:rejectOrder }

myshop.add_product_to_basket:
    path:   /basket/product/{idProduct}/buy
    defaults: { _controller: MyShopDefaultBundle:Basket:addProductToBasket }
    requirements:
        idProduct: \d+

myshop.curl_client_json_rpc:
    path:   /client/jsonrpc/{idProduct}
    defaults: { _controller: MyShopDefaultBundle:Default:clientCurl }
    requirements:
        idProduct: \d+

myshop.page:
    path:   /{pageKey}
    defaults: { _controller: MyShopDefaultBundle:Page:index }